twig:
    paths:
        '%kernel.project_dir%/templates': Temp
        "%kernel.root_dir%/../templates": Templates
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    globals:
        app_name: '%env(APP_NAME)%'
        app_color: '%env(APP_COLOR)%'
        base_url: '%env(BASE_URL)%'
        app_version: '%env(APP_VERSION)%'
